# Generated by Django 5.1.6 on 2026-01-26 12:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(default='', max_length=255)),
                ('cidade', models.CharField(default='', max_length=255)),
                ('uf', models.CharField(choices=[('AC', 'AC - Acre'), ('AL', 'AL - Alagoas'), ('AP', 'AP - Amapá'), ('AM', 'AM - Amazonas'), ('BA', 'BA - Bahia'), ('CE', 'CE - Ceará'), ('DF', 'DF - Distrito Federal'), ('ES', 'ES - Espírito Santo'), ('GO', 'GO - Goiás'), ('MA', 'MA - Maranhão'), ('MT', 'MT - Mato Grosso'), ('MS', 'MS - Mato Grosso do Sul'), ('MG', 'MG - Minas Gerais'), ('PA', 'PA - Pará'), ('PB', 'PB - Paraíba'), ('PR', 'PR - Paraná'), ('PE', 'PE - Pernambuco'), ('PI', 'PI - Piauí'), ('RJ', 'RJ - Rio de Janeiro'), ('RN', 'RN - Rio Grande do Norte'), ('RS', 'RS - Rio Grande do Sul'), ('RO', 'RO - Rondônia'), ('RR', 'RR - Roraima'), ('SC', 'SC - Santa Catarina'), ('SP', 'SP - São Paulo'), ('SE', 'SE - Sergipe'), ('TO', 'TO - Tocantins')], default='AC', max_length=2)),
                ('nome_responsavel', models.CharField(default='', max_length=255)),
                ('email_responsavel', models.CharField(default='', max_length=255)),
                ('tratamento_responsavel', models.CharField(choices=[('Sr', 'Sr'), ('Sra', 'Sra')], default='Sr', max_length=3)),
                ('status', models.CharField(choices=[('ATIVA', 'ATIVA'), ('SUSPENSA', 'SUSPENSA'), ('REJEITADA', 'REJEITADA')], default='ATIVA', max_length=14)),
                ('criacao', models.DateTimeField(auto_now=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=55, verbose_name='Ação Realizada')),
                ('user', models.CharField(max_length=255, verbose_name='Usuário da Ação')),
                ('momento', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('numero_pagina_servicos', models.IntegerField(default=0)),
                ('numero_pagina_adicionais', models.IntegerField(default=0)),
                ('numero_pagina_equipamentos', models.IntegerField(default=0)),
                ('filename', models.CharField(default='', max_length=255)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('valor_servico', models.FloatField()),
                ('tipo', models.CharField(choices=[('Equipamento', 'Locação de Equipamentos / SaaS'), ('Serviço', 'Serviço'), ('Adicional', 'Variavel')], default='Serviço', max_length=14)),
                ('status', models.CharField(choices=[('ATIVA', 'ATIVA'), ('SUSPENSA', 'SUSPENSA')], default='ATIVA', max_length=14)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='InfosUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('Comercial Manager', 'Comercial Manager'), ('Assistente Comercial', 'Assistente Comercial'), ('Diretor Comercial', 'Diretor Comercial'), ('Diretor', 'Diretor'), ('CEO', 'CEO')], default='Comercial Manager', max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('modelo', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ATIVA', 'ATIVA'), ('SUSPENSA', 'SUSPENSA'), ('REJEITADA', 'REJEITADA')], default='ATIVA', max_length=14)),
                ('tempo_de_contrato', models.IntegerField(default=24)),
                ('valor_dolar', models.CharField(default='0,00', max_length=24)),
                ('numero_proposta', models.CharField(default='', max_length=25)),
                ('observacoes_equipamento', models.TextField(default='')),
                ('observacoes_servicos', models.TextField(default='')),
                ('observacoes_adicionais', models.TextField(default='')),
                ('tipo_cobranca_equipamento', models.BooleanField(default=False)),
                ('tipo_cobranca_servico', models.BooleanField(default=False)),
                ('tipo_cobranca_adicional', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=255)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='propostas', to='core.cliente')),
                ('usuario_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoProposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('descricao', models.TextField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('Serviço', 'Serviço'), ('Equipamento', 'Locação de Equipamentos / SaaS'), ('Adicional', 'Adicional')], default='Serviço', max_length=55)),
                ('proposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.proposta')),
            ],
        ),
    ]
